{"uuid": "d42665ff-0bdc-447f-a959-f86fbdde4464", "children": ["173bca5e-538d-4fba-9928-45a7048ef2bc", "a6680329-d31f-46e9-b4f4-36e9a084e1c6", "6c89d3ea-b344-4af4-aa88-ea73a076e606"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='114.115.205.214', port=8686): Max retries exceeded with url: /Ecan_Platform/loginAction!loginSystem.action (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E1764E72B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\_pytest\\python.py\", line 701, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\_pytest\\python.py\", line 632, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\亿能达\\测试\\测试框架\\demo_pytest_接口\\testcase\\case\\test_ZcZcrk.py\", line 22, in setup_class\n    BasePage.login()        #先获取登录cookie和设置好请求头\n  File \"D:\\亿能达\\测试\\测试框架\\demo_pytest_接口\\base\\BasePage.py\", line 33, in login\n    response1 = requests.post(url=url, data=data, headers=headers)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\requests\\api.py\", line 119, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\requests\\api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\requests\\sessions.py\", line 530, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\requests\\sessions.py\", line 643, in send\n    r = adapter.send(request, **kwargs)\n  File \"d:\\亿能达\\测试\\测试框架\\python霍格沃兹\\venv\\lib\\site-packages\\requests\\adapters.py\", line 516, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1611041195326, "stop": 1611041197640}], "start": 1611041195326, "stop": 1611041198335}